export enum ResponseCode {
  SUCCESS = 'SUCCESS',
  CREATED = 'CREATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_ROUTE_NOT_FOUND = 'ERR_ROUTE_NOT_FOUND',
  ERR_ACTION_UNAUTHORIZED = 'ERR_ACTION_UNAUTHORIZED',
  ERR_INVALID_ACTION = 'ERR_INVALID_ACTION',
  ERR_INVALID_STATUS = 'ERR_INVALID_STATUS',
  ERR_AUTHENTICATION = 'ERR_AUTHENTICATION',
  ERR_INVALID_QUERY_PARAMETER = 'ERR_INVALID_QUERY_PARAMETER',
  ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
  ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',
}